version: '4'

services:
  # Database
  db2:
    image: mysql:latest
    volumes: 
      - db2_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: process.env.MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: process.env.MYSQL_DATABASE
      MYSQL_USER: process.env.MYSQL_USER
      MYSQL_PASSWORD: process.env.MYSQL_PASSWORD
    networks:
      - frontityresumesite

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db2
    image: phpmyadmin:latest
    restart: always
    ports: 
      - '8082:80'
    environment:
      PMA_HOST: db2
      MYSQL_ROOT_PASSWORD: process.env.MYSQL_ROOT_PASSWORD
    networks:
      - frontityresumesite

  # Wordpress
  wordpress:
    depends_on:
      - db2
    image: wordpress:latest
    ports:
      - '8002:80'
    restart: always
    volumes: ['./:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db2:3306
      WORDPRESS_DB_USER: process.env.WORDPRESS_DB_USER
      WORDPRESS_DB_PASSWORD: process.env.WORDPRESS_DB_PASSWORD
    networks:
      - frontityresumesite
networks: 
  frontityresumesite:
volumes: 
  db2_data: 

