version: '3'

services:
  # Database
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: process.env.MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: process.env.MYSQL_DATABASE
      MYSQL_USER: process.env.MYSQL_USER
      MYSQL_PASSWORD: process.env.MYSQL_PASSWORD
    networks:
      - frontitysite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: process.env.MYSQL_ROOT_PASSWORD
    networks:
      - frontitysite

    # Enable emulation for the phpmyadmin service
    command: ["qemu", "qemu-system-x86_64", "-cpu", "host", "-vnc", ":0"]
    # Mount QEMU binaries into the container
    volumes:
      - /usr/bin/qemu-x86_64-static:/usr/bin/qemu-x86_64-static
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '8001:80'
    restart: always
    volumes: ['./:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db:3307
      WORDPRESS_DB_USER: process.env.WORDPRESS_DB_USER
      WORDPRESS_DB_PASSWORD: process.env.WORDPRESS_DB_PASSWORD
    networks:
      - frontitysite
networks:
  frontitysite:
volumes:
  db_data: