version: '3.8'

services:
  # Database
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: frontityPassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: frontityWordpress
      MYSQL_PASSWORD: frontityWordpress
    networks:
      - frontitysite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: frontityPassword
    networks:
      - frontitysite
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '8001:80'
    restart: always
    # Web route for Apache, which is used by WP
    volumes: ['./:/var/www/html']
    environment:
      # host is db service
      # 3306 is default port for mysql
      WORDPRESS_DB_HOST: db:3306
      # must match mysql user and password
      WORDPRESS_DB_USER: frontity
      WORDPRESS_DB_PASSWORD: frontity
    networks:
      - frontitysite
networks:
  frontitysite:
volumes:
  db_data: